# Generated by Django 6.0.3 on 2026-03-26 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_batch_classsession_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='generation_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classsession',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='last_generated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 26, 17, 47, 30, 34651, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
