# Generated by Django 6.0.3 on 2026-03-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_classsession_generation_count_classsession_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_markings', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='session_type',
            field=models.CharField(choices=[('CLASS', 'Regular Class'), ('EXAM', 'Examination'), ('EVENT', 'College Event')], default='CLASS', max_length=10),
        ),
    ]
